/**
 * @author Pradip Sahoo
 * Created on 11/08/2022
 * -------------------------
 * Find the Difference
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * Return the letter that was added to t.
 * 
 * Example 1:
 *  Input: s = "abcd", t = "abcde"
 *  Output: "e"
 *  Explanation: 'e' is the letter that was added.
 * 
 * Example 2:
 *  Input: s = "", t = "y"
 *  Output: "y"
 * 
 * Time Complexity : O(N)
 * Space Complexity : O(1)
 */
package Love_Babbar_DSA_Sheet.String.Easy_Questions;

import java.util.Scanner;

public class Q01_DifferenceBetweenTwoString {

    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);

        System.out.print("Enter the first string : ");
        String str_1 = sc.nextLine();

        System.out.print("Enter the second string : ");
        String str_2 = sc.nextLine();

        sc.close();
        System.out.println("The newly added letter is : " + findDifference(str_1, str_2));
    }

    /**
     * Method to find the difference between two string
     * 
     * @param str_1
     * @param str_2
     * @return the newly added character
     */
    private static char findDifference(String str_1, String str_2) {
        char newText = 0;
        for (char itr1 : str_1.toCharArray()) {
            newText ^= itr1;
        }
        for (char itr2 : str_2.toCharArray()) {
            newText ^= itr2;
        }
        return newText;
    }
}