/**
 * Find the difference of two string.
 * 
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 * 
 * Example :
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 */
package String.StringBasicQuestions;

import java.util.Scanner;

public class FindTheDifference {

    public static void main(String[] args) {

        // Create Scanner class object to take user input
        Scanner sc = new Scanner(System.in);

        // Ask user to enter the first string
        System.out.print("Enter the first string : ");
        String str1 = sc.nextLine();

        // Ask user to enter the second string
        System.out.print("Enter the second string : ");
        String str2 = sc.nextLine();

        sc.close();

        // Method call to find the newly added letter or difference and print it
        System.out.println("The newly added letter is : " + findDifference(str1, str2));
    }

    // Method to find the difference or newly added letter of two string
    private static char findDifference(String s, String t) {

        // Find the length of the first string
        int len = s.length();

        // Declare a char variable which is store the last element of the first string
        char addedLetter = t.charAt(len);

        for (int i = 0; i < len; i++) {
            addedLetter ^= (s.charAt(i) ^ t.charAt(i));
        }

        return addedLetter;
    }
}